/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Juego;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileReader;
import java.util.Base64;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author unkndown
 */
public class Configuracion extends javax.swing.JFrame {
    
    // minim y maximo en tablero
    private int minimo=8,maximo=40;
    
    
    /**
     * Creates new form Configuracion
     */
    public Configuracion() {
        // Convertir a mayusculas el nickname
        initComponents();
        this.setLocationRelativeTo(null);

        // Niveles
        String[] niveles = {"Fácil", "Intermedio", "Difícil", "Personalizado"};
        selectNivel.setModel(new javax.swing.DefaultComboBoxModel<>(niveles));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        porcentajeBombasTitulo = new javax.swing.JLabel();
        porcentajeBombasSlider = new javax.swing.JSlider();
        porcentajeBombasValor = new javax.swing.JLabel();
        mensajeConfiguracion = new javax.swing.JLabel();
        nickNameJugador = new javax.swing.JLabel();
        selectTitulo = new javax.swing.JLabel();
        selectNivel = new javax.swing.JComboBox<>();
        inputColumnas = new javax.swing.JTextField();
        inputFilas = new javax.swing.JTextField();
        startGame = new javax.swing.JButton();
        cargarPartida = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Configuracion");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        porcentajeBombasTitulo.setText("Porcentaje de bombas:");
        getContentPane().add(porcentajeBombasTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, 29));

        porcentajeBombasSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                porcentajeBombasSliderStateChanged(evt);
            }
        });
        getContentPane().add(porcentajeBombasSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 149, -1));

        porcentajeBombasValor.setText("50%");
        getContentPane().add(porcentajeBombasValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, -1, 29));

        mensajeConfiguracion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mensajeConfiguracion.setText("Porfavor Configura el juego a tu gusto");
        getContentPane().add(mensajeConfiguracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 414, -1));

        nickNameJugador.setFont(new java.awt.Font("Marker Felt", 0, 36)); // NOI18N
        nickNameJugador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nickNameJugador.setText("Matias");
        getContentPane().add(nickNameJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 414, -1));

        selectTitulo.setText("Selecciona la dificultad:");
        getContentPane().add(selectTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        selectNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        selectNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectNivelActionPerformed(evt);
            }
        });
        getContentPane().add(selectNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 186, -1));

        inputColumnas.setEditable(false);
        inputColumnas.setBackground(new java.awt.Color(248, 194, 70));
        inputColumnas.setForeground(new java.awt.Color(255, 255, 255));
        inputColumnas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputColumnas.setText("10");
        inputColumnas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Columnas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N
        inputColumnas.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        getContentPane().add(inputColumnas, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 162, 68));

        inputFilas.setEditable(false);
        inputFilas.setBackground(new java.awt.Color(248, 194, 70));
        inputFilas.setForeground(new java.awt.Color(255, 255, 255));
        inputFilas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputFilas.setText("10");
        inputFilas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N
        inputFilas.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        getContentPane().add(inputFilas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 162, 68));

        startGame.setText("Empezar Juego");
        startGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startGameMouseClicked(evt);
            }
        });
        startGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startGameActionPerformed(evt);
            }
        });
        getContentPane().add(startGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        cargarPartida.setText("Cargar Partida");
        cargarPartida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cargarPartidaMouseClicked(evt);
            }
        });
        getContentPane().add(cargarPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, -1, -1));

        jLabel1.setText("UnknDown ®");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel2.setText("Taller de Programacion ll");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/fondo_general.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, -4, 440, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startGameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startGameActionPerformed

    private void startGameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startGameMouseClicked
        // inicar nuevo Juego
        if(Integer.parseInt(inputFilas.getText()) >= minimo && Integer.parseInt(inputColumnas.getText()) >=minimo)
        {
            if(Integer.parseInt(inputFilas.getText()) <= maximo && Integer.parseInt(inputColumnas.getText()) <= maximo)
            {
                int nueva = JOptionPane.showConfirmDialog(null, "Iniciar una nueva partida?");
                if (nueva == 0) {
                    BuscaMinas ventanajuego = new BuscaMinas();
                    ventanajuego.porcentajeMinas = porcentajeBombasSlider.getValue();
                    ventanajuego.filas = Integer.parseInt(inputFilas.getText());
                    ventanajuego.columnas = Integer.parseInt(inputColumnas.getText());
                    ventanajuego.inicio();
                    ventanajuego.setVisible(true);
                    ventanajuego.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    this.setVisible(false);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "El máximo debe ser "+maximo+"x"+maximo);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "El minimo debe ser "+minimo+"x"+minimo);
        }
    }//GEN-LAST:event_startGameMouseClicked

    private void selectNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectNivelActionPerformed
        String dificultad = selectNivel.getSelectedItem().toString();

        switch (dificultad) {
            case "Fácil":
                inputFilas.setText("10");
                inputColumnas.setText("10");
                inputFilas.setEditable(false);
                inputColumnas.setEditable(false);
                break;
            case "Intermedio":
                inputFilas.setText("18");
                inputColumnas.setText("18");
                inputFilas.setEditable(false);
                inputColumnas.setEditable(false);
                break;
            case "Difícil":
                inputFilas.setText("25");
                inputColumnas.setText("25");
                inputFilas.setEditable(false);
                inputColumnas.setEditable(false);
                break;
            case "Personalizado":
                inputFilas.requestFocus();
                inputFilas.setEditable(true);
                inputColumnas.setEditable(true);
                break;

        }
    }//GEN-LAST:event_selectNivelActionPerformed

    private void porcentajeBombasSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_porcentajeBombasSliderStateChanged
        // TODO add your handling code here:
        porcentajeBombasValor.setText(Integer.toString(porcentajeBombasSlider.getValue()) + "%");
    }//GEN-LAST:event_porcentajeBombasSliderStateChanged

    private void cargarPartidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cargarPartidaMouseClicked
        BuscaMinas ventanajuego = new BuscaMinas();
        javax.swing.JFileChooser jF1 = new javax.swing.JFileChooser();

        try {
            if (jF1.showOpenDialog(null) == jF1.APPROVE_OPTION) {
                String ruta = jF1.getSelectedFile().getAbsolutePath();
                // verificar que es una partida
                BufferedReader partida = new BufferedReader(new FileReader(ruta));
                String datos = partida.readLine().trim();
                partida.close();
                byte[] decodedBytes = Base64.getDecoder().decode(datos.getBytes());
                ventanajuego.ruta = ruta;
                int load = JOptionPane.showConfirmDialog(null, "Iniciar una partida guardada?");
                
                if(load==0)
                {
                    try {
                        ventanajuego.cargar();
                    } catch (Exception ex) {
                        System.out.println(ex);
                    }
                    ventanajuego.setVisible(true);
                    ventanajuego.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    this.setVisible(false);
                }
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "No es una partida válida");
        }


    }//GEN-LAST:event_cargarPartidaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
            e.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Configuracion().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cargarPartida;
    private javax.swing.JLabel fondo;
    private javax.swing.JTextField inputColumnas;
    private javax.swing.JTextField inputFilas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel mensajeConfiguracion;
    public static javax.swing.JLabel nickNameJugador;
    private javax.swing.JSlider porcentajeBombasSlider;
    private javax.swing.JLabel porcentajeBombasTitulo;
    private javax.swing.JLabel porcentajeBombasValor;
    private javax.swing.JComboBox<String> selectNivel;
    private javax.swing.JLabel selectTitulo;
    private javax.swing.JButton startGame;
    // End of variables declaration//GEN-END:variables
}
